### ISSUE TITLE
No Armor protect

### ISSUE THREAD

**Issue by SuperAdam47** [InfinityGamers/Gears#11]
chest: 299:0:1:default:protection:1

![image](https://user-images.githubusercontent.com/16169771/43518920-37b56d80-9596-11e8-8d69-fdfdf14764fb.png)

armor effects not work

**Comment by xBeastMode** [comment]
Can you give me the `special_kits.yml` content?

**Comment by SuperAdam47** [comment]
ok

**Comment by SuperAdam47** [comment]
[special_kits.zip](https://github.com/InfinityGamers/Gears/files/2254319/special_kits.zip)

**Comment by xBeastMode** [comment]
![capture---11](https://user-images.githubusercontent.com/16060686/43618544-93756fe6-968e-11e8-9090-ba583515bc36.PNG)
Works for me are you sure you're using latest pocketmine?

**Comment by SuperAdam47** [comment]
I am using Altay

**Comment by xBeastMode** [comment]
Sorry, but this plugin is only supported by PocketMine.
