### ISSUE TITLE
Permissions?

### ISSUE THREAD

**Issue by AlexPads** [InfinityGamers/Gears#14]
Hello!!!
I love this plugin! the effects are great!
can you please tell me how to give people permission to the kits because as it is right now when people get the kit on my server they do /gear and it shows that they have that kit but when they do /gear Thor (for example) it says that they need permission any ideas??

given permission: gear.thor and gear.Thor (to test)
MCPE: Win10/Android/(IOS not tested)
PHP: 7.2
Pocketmine: version 3.2.3 (newest)
Hosted at a place :)

ask to get IP for server so we can try things :p (didn't want to advertise 0_0 )
 
Thanks hope to hear from you soon!!!!

**Comment by xBeastMode** [comment]
Are you using a permissions plugin? If so which and what version of it?

**Comment by AlexPads** [comment]
i am using Pure perms latest (1.4.2)

**Comment by AlexPads** [comment]
Happy to help :)

**Comment by xBeastMode** [comment]
Thanks, I will check if it's an issue from this plugin.

**Comment by salllaf** [comment]
Hello, did either of you ever figure out if this was interference with another plugin or what? I'm running into the same issues. Thank you for sharing the Awesome plugin btw :))

**Comment by AlexPads** [comment]
I think that it is just a Permission mistake :) ~sallaf

**Comment by xBeastMode** [comment]
Ok I think I figured out the problem now, it's do to changes in the API, which also brings in breaking changes to the plugin so I will need some time to update it.
